### ISSUE TITLE
SVM implementation in Javascript

### ISSUE THREAD

**Issue by Hack3l** [Rostlab/JS16_ProjectB_Group6#17]
- [x] Find good svm package
- [ ] Implement SVM
- [ ] Find best settings for SVM
- [ ] Test SVM with selected features
- [ ] Store plod and feature contribution

**Comment by Hack3l** [comment]
SVM package we want to use : https://github.com/nicolaspanel/node-svm

**Comment by goldbergtatyana** [comment]
Basically, we don't need any other machine learning tool other than weka

**Comment by Hack3l** [comment]
@goldbergtatyana so we should use node-weka instead?

**Comment by goldbergtatyana** [comment]
@Hack3l not even that. Once you found your optimal prediction model, you save the result of it and you're done. So, there is really no need running any JS weka implementations or other JS-based machine learning tools (only if you want to experiment with them :)).

**Comment by subburamr** [comment]
Closing the issue as it is not being implemented now.
