### ISSUE TITLE
Data flow and storage

### ISSUE THREAD

**Issue by sacdallago** [Rostlab/JS16_ProjectB_Group6#26]
In an effort to bring together the pieces, we came up with the following requirements:

The predictions that you will produce will be bound to a character, say

```
{
  name: "Some character",
  ...,
  PLOD6: //YOUR NORMALIZED PLOD HERE,
  PLOD7: // B7's PLOD here
}
```

As the PLOD for a character will be a numerical value and the machine learning will only train on the available data now, so it makes no sense for you to create PLODs dynamically.

You will write directly on the database that **A** uses that should be somewhere on mLab. If @kordianbruck is using his own server to store the data, please come up with some idea.

@AlexMoroz I assigned the issue to you because **E** should supervise this, but defer commitment to one of your teammates.

**Comment by AlexMoroz** [comment]
@CavidSalahov  assign it to yourself =)
I don't have access to repo.
