### ISSUE TITLE
Project Package via NPM

### ISSUE THREAD

**Issue by kordianbruck** [Rostlab/JS16_ProjectB_Group6#29]
Please provide your NPM package as soon as possible!

**Comment by jsalahov** [comment]
@sacdallago Should I set the publishing from master branch or according to tags on develop?

**Comment by kordianbruck** [comment]
@CavidSalahov please only use stable commit states. Either master with tags or just master. Tags actually define a released version in the normal git workflow.

**Comment by jsalahov** [comment]
K. Setting up deploy from master branch. Meanwhile, you can use npm to install from github.

**Comment by jsalahov** [comment]
@asesselmann @Hack3l @subburamr @ThuyNganTran Guys, please choose a package name starting with "got".

**Comment by asesselmann** [comment]
I suggest gotPLOD

**Comment by kordianbruck** [comment]
@asesselmann Can you give me some instructions how to include it or link to the NPM page?

**Comment by asesselmann** [comment]
Sorry, I can't. Maybe one of the others can help you?
@Hack3l @subburamr @ThuyNganTran

**Comment by sacdallago** [comment]
You forgot the most important one: @CavidSalahov

**Comment by jsalahov** [comment]
@kordianbruck Experimental (because I don't even remember what was the state of the project when it was published) package is available here:
https://www.npmjs.com/package/gotplod
But you're better off installing directly from github (npm can do that), as next deployment configured to be from master branch

**Comment by gyachdav** [comment]
C'mon they're all important <3
