### ISSUE TITLE
Make npm package

### ISSUE THREAD

**Issue by jsalahov** [Rostlab/JS16_ProjectB_Group6#4]
Add package.json

**Comment by sacdallago** [comment]
@CavidSalahov remember:
`If the commit is in a non-default branch, the issue will remain open and the issue will be referenced with a tooltip.`
https://help.github.com/articles/closing-issues-via-commit-messages/

I actually don't know if once you merge the feature branch into the default branch (develop), it will close this issue. Keep an eye on it and let me know :) I'm very curious

**Comment by jsalahov** [comment]
Well, looks like it worked :)

**Comment by sacdallago** [comment]
Very nice!
