### ISSUE TITLE
Popularity from API?

### ISSUE THREAD

**Issue by Hack3l** [Rostlab/JS16_ProjectB_Group6#61]
@sacdallago Should we change the populartity (page rank) to be taken from the api?
only asking because feature freeze was on monday.

**Comment by gyachdav** [comment]
that should be fine. feature freeze === not developing new features. fixing/improving existing features is fine.

**Comment by sacdallago** [comment]
Agree with guy. If it doesn't mean a major change in functionality then this can be done and should also look nicer as we/you avoid redundancy :)
Thanks for asking!

**Comment by Hack3l** [comment]
ok thanks
